### ISSUE TITLE
Unable to create new note

### ISSUE THREAD

**Issue by panixx** [foxmask/joplin-web#22]
When trying to save a new note, it does not work. It loads notes/notebooks fine, but not saving.  Relevant log output is below:

2019-09-03 15:21:44,039 - INFO - ('192.168.1.1', 41453) - "POST /api/jw/notes/ HTTP/1.1" 500
2019-09-03 15:21:44,039 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 177, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 155, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 352, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 352, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 352, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/app/app.py", line 209, in create_notes
    parent_id = payload['parent_id']
KeyError: 'parent_id'

**Comment by panixx** [comment]
Should note I am using the docker image and tested using python 3.6 and 3.7 with same results.  Joplin being used is the joplin-cli with the headless server branch here: https://github.com/laurent22/joplin/tree/headless-server

**Comment by panixx** [comment]
Was looking over the source and noticed the source used was not the official. Will test the official source and reopen issue if needed.

**Comment by panixx** [comment]
Did more testing on this using the Joplin Desktop app on linux to make sure it wasnt an issue with the cli version.  Same error occurs. I hardcoded 'parent_id': 1 in the addNote function in TakeNote.vue and was able to get a note to save, so something is going on with how it's getting the parent_id for this.parent_id.

**Comment by foxmask** [comment]
you spotted an issue related to vue-treeselect i didnt not have before to add it
I'm digging
