### ISSUE TITLE
Can't build on Ubuntu 18.04

### ISSUE THREAD

**Issue by anhofmann** [foxmask/joplin-web#62]
I'm trying to install joplin-web on Ubuntu 18.04, but I can't get it to run. 

There are multiple problems that I tried to work around.
First problem: a path is not where it should be.
README tells me to do this: 
> pip install -r requirements.txt
> cd ../joplin-vue
> npm install

but the path joplin-vue is in ./ not in ../ I tried to move the folder, but it made no difference.

second problem: running `npm run build` leads to this: 

```
ERROR  Failed to compile with 1 errors                                                                                                                                                         9:23:33 PM

  Error: TypeError [ERR_INVALID_URL]: Invalid URL: http://0.0.0.0:8001undefinedstatic/css/chunk-vendors.css
  
  - url.js:257 onParseError
    internal/url.js:257:9
  
  - url.js:333 new URL
    internal/url.js:333:5
  
  - determine-as-value.js:39 determineAsValue
    [joplin-vue]/[@vue]/preload-webpack-plugin/src/lib/determine-as-value.js:39:19
  
  - index.js:77 PreloadPlugin.generateLinks
    [joplin-vue]/[@vue]/preload-webpack-plugin/src/index.js:77:25
  
  - index.js:120 
    [joplin-vue]/[@vue]/preload-webpack-plugin/src/index.js:120:18
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [joplin-vue]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 promisedApplyPluginsAsyncWaterfall
    [joplin-vue]/[html-webpack-plugin]/index.js:673:47
  
  - index.js:178 
    [joplin-vue]/[html-webpack-plugin]/index.js:178:18
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joplin-vue@1.0.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the joplin-vue@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2020-05-14T19_23_33_719Z-debug.log
```

The debug logfile contains this: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle joplin-vue@1.0.0~prebuild: joplin-vue@1.0.0
6 info lifecycle joplin-vue@1.0.0~build: joplin-vue@1.0.0
7 verbose lifecycle joplin-vue@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle joplin-vue@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/me/joplin-web/joplin-vue/node_modules/.bin:/home/me/joplin-web/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle joplin-vue@1.0.0~build: CWD: /home/me/joplin-web/joplin-vue
10 silly lifecycle joplin-vue@1.0.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle joplin-vue@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle joplin-vue@1.0.0~build: Failed to exec build script
13 verbose stack Error: joplin-vue@1.0.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid joplin-vue@1.0.0
15 verbose cwd /home/me/joplin-web/joplin-vue
16 verbose Linux 5.3.0-51-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error joplin-vue@1.0.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the joplin-vue@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I had more problems when trying to install requirements.txt with doing this: `pip3 install wheel` and `pip install wheel`

Can you help me with this?

**Comment by foxmask** [comment]
Hi,

> but the path joplin-vue is in ./ not in ../ I tried to move the folder, but it made no difference.
try
```
python3 -m venv joplin-web
cd joplin-web
source bin/activate
git clone https://github.com/foxmask/joplin-web
cd joplin-web
pip install -r requirements.txt
cd joplin-vue
npm install
```
once we've just cloned the project and enter in the joplin-web folder, we have the sub folder joplin-vue just in the current folder

> second problem: running npm run build leads to this:

you did not set the environment variable before as said in the [joplin-vue/README.md](https://github.com/foxmask/joplin-web/blob/master/joplin-vue/README.md)
for example 
```
export JW_BASE_URL='/'
```
then 
```
npm run build
```
