### ISSUE TITLE
Error with production build

### ISSUE THREAD

**Issue by geca** [foxmask/joplin-web#68]
Doing `npm run build` I get

```
ERROR  Failed to compile with 1 errors

    Error: TypeError [ERR_INVALID_URL]: Invalid URL: http://0.0.0.0:8001undefinedstatic/css/chunk-vendors.css
```
Any idea what could be wrong?

Here's the whole debug output:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/geca/.nvm/versions/node/v10.15.1/bin/node',
1 verbose cli   '/home/geca/.nvm/versions/node/v10.15.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle joplin-vue@1.0.0~prebuild: joplin-vue@1.0.0
6 info lifecycle joplin-vue@1.0.0~build: joplin-vue@1.0.0
7 verbose lifecycle joplin-vue@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle joplin-vue@1.0.0~build: PATH: /home/geca/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/geca/code/joplin-web/joplin-vue/node_modules/.bin:/home/geca/.nvm/versions/node/v10.15.1/bin:/home/geca/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle joplin-vue@1.0.0~build: CWD: /home/geca/code/joplin-web/joplin-vue
10 silly lifecycle joplin-vue@1.0.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle joplin-vue@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle joplin-vue@1.0.0~build: Failed to exec build script
13 verbose stack Error: joplin-vue@1.0.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/geca/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/geca/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid joplin-vue@1.0.0
15 verbose cwd /home/geca/code/joplin-web/joplin-vue
16 verbose Linux 5.6.11-1-MANJARO
17 verbose argv "/home/geca/.nvm/versions/node/v10.15.1/bin/node" "/home/geca/.nvm/versions/node/v10.15.1/bin/npm" "run" "build"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error joplin-vue@1.0.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the joplin-vue@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by geca** [comment]
Duplicate: https://github.com/foxmask/joplin-web/issues/62
